// <auto-generated />
using FAQ.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FAQ.Migrations
{
    [DbContext(typeof(FaqsContext))]
    partial class FaqsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FAQ.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "gen",
                            Name = "General"
                        },
                        new
                        {
                            CategoryId = "hist",
                            Name = "History"
                        });
                });

            modelBuilder.Entity("FAQ.Models.FAQ", b =>
                {
                    b.Property<int>("FAQId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FAQId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FAQId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            FAQId = 1,
                            Answer = "ASP.NET Core is a cross-platform, high-performance framework for building modern, cloud-based, Internet-connected applications.",
                            CategoryId = "gen",
                            Question = "What is ASP.NET Core?",
                            TopicId = "asp"
                        },
                        new
                        {
                            FAQId = 2,
                            Answer = "Blazor is a framework for building interactive client-side web UI with .NET.",
                            CategoryId = "gen",
                            Question = "What is Blazor?",
                            TopicId = "blz"
                        },
                        new
                        {
                            FAQId = 3,
                            Answer = "Entity Framework (EF) is an open source object-relational mapping (ORM) framework for ADO.NET.",
                            CategoryId = "gen",
                            Question = "What is Entity Framework?",
                            TopicId = "ef"
                        },
                        new
                        {
                            FAQId = 4,
                            Answer = "ASP.NET Core was first released in 2016.",
                            CategoryId = "hist",
                            Question = "When was ASP.NET Core first released?",
                            TopicId = "asp"
                        },
                        new
                        {
                            FAQId = 5,
                            Answer = "Blazor was first released in 2020.",
                            CategoryId = "hist",
                            Question = "When was Blazor first released?",
                            TopicId = "blz"
                        },
                        new
                        {
                            FAQId = 6,
                            Answer = "Entity Framework was first released in 2008.",
                            CategoryId = "hist",
                            Question = "When was Entity Framework first released?",
                            TopicId = "ef"
                        });
                });

            modelBuilder.Entity("FAQ.Models.Topic", b =>
                {
                    b.Property<string>("TopicId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicId = "asp",
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            TopicId = "blz",
                            Name = "Blazor"
                        },
                        new
                        {
                            TopicId = "ef",
                            Name = "Entity Framework"
                        });
                });

            modelBuilder.Entity("FAQ.Models.FAQ", b =>
                {
                    b.HasOne("FAQ.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FAQ.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Topic");
                });
#pragma warning restore 612, 618
        }
    }
}
